import type { CatalogExercise, InjuryFlag } from "./types";

/** Розширений каталог (slug → метадані; id з БД підставляється при генерації) */
export const EXERCISE_CATALOG: CatalogExercise[] = [
  {
    slug: "bench-press",
    name: "Жим штанги лежачи",
    category: "CHEST",
    equipment: "BARBELL",
    compound: true,
    avoidInjuries: ["SHOULDER"],
    priority: 10,
  },
  {
    slug: "incline-db-press",
    name: "Жим гантелей на похилій",
    category: "CHEST",
    equipment: "DUMBBELL",
    compound: true,
    avoidInjuries: ["SHOULDER"],
    priority: 8,
  },
  {
    slug: "push-ups",
    name: "Віджимання",
    category: "CHEST",
    equipment: "BODYWEIGHT",
    compound: true,
    avoidInjuries: ["WRIST", "SHOULDER"],
    priority: 7,
  },
  {
    slug: "cable-fly",
    name: "Зведення в кросовері",
    category: "CHEST",
    equipment: "CABLE",
    compound: false,
    avoidInjuries: ["SHOULDER"],
    priority: 6,
  },
  {
    slug: "pull-ups",
    name: "Підтягування",
    category: "BACK",
    equipment: "BODYWEIGHT",
    compound: true,
    avoidInjuries: ["ELBOW"],
    priority: 10,
  },
  {
    slug: "barbell-row",
    name: "Тяга штанги в нахилі",
    category: "BACK",
    equipment: "BARBELL",
    compound: true,
    avoidInjuries: ["LOWER_BACK"],
    priority: 9,
  },
  {
    slug: "lat-pulldown",
    name: "Тяга верхнього блоку",
    category: "BACK",
    equipment: "CABLE",
    compound: true,
    avoidInjuries: [],
    priority: 8,
  },
  {
    slug: "deadlift",
    name: "Станова тяга",
    category: "BACK",
    equipment: "BARBELL",
    compound: true,
    avoidInjuries: ["LOWER_BACK", "HIP", "KNEE"],
    priority: 9,
  },
  {
    slug: "db-row",
    name: "Тяга гантелі в нахилі",
    category: "BACK",
    equipment: "DUMBBELL",
    compound: true,
    avoidInjuries: ["LOWER_BACK"],
    priority: 7,
  },
  {
    slug: "squat",
    name: "Присідання зі штангою",
    category: "LEGS",
    equipment: "BARBELL",
    compound: true,
    avoidInjuries: ["KNEE", "LOWER_BACK", "HIP"],
    priority: 10,
  },
  {
    slug: "leg-press",
    name: "Жим ногами",
    category: "LEGS",
    equipment: "MACHINE",
    compound: true,
    avoidInjuries: ["KNEE", "LOWER_BACK"],
    priority: 9,
  },
  {
    slug: "rdl",
    name: "Румунська станова",
    category: "LEGS",
    equipment: "BARBELL",
    compound: true,
    avoidInjuries: ["LOWER_BACK", "KNEE"],
    priority: 8,
  },
  {
    slug: "lunges",
    name: "Випади з гантелями",
    category: "LEGS",
    equipment: "DUMBBELL",
    compound: true,
    avoidInjuries: ["KNEE"],
    priority: 7,
  },
  {
    slug: "leg-curl",
    name: "Згинання ніг у тренажері",
    category: "LEGS",
    equipment: "MACHINE",
    compound: false,
    avoidInjuries: ["KNEE"],
    priority: 6,
  },
  {
    slug: "calf-raise",
    name: "Підйом на носки",
    category: "LEGS",
    equipment: "MACHINE",
    compound: false,
    avoidInjuries: [],
    priority: 5,
  },
  {
    slug: "ohp",
    name: "Жим штанги стоячи",
    category: "SHOULDERS",
    equipment: "BARBELL",
    compound: true,
    avoidInjuries: ["SHOULDER", "LOWER_BACK"],
    priority: 8,
  },
  {
    slug: "db-shoulder-press",
    name: "Жим гантелей сидячи",
    category: "SHOULDERS",
    equipment: "DUMBBELL",
    compound: true,
    avoidInjuries: ["SHOULDER"],
    priority: 9,
  },
  {
    slug: "lateral-raise",
    name: "Махи гантелей в сторони",
    category: "SHOULDERS",
    equipment: "DUMBBELL",
    compound: false,
    avoidInjuries: ["SHOULDER"],
    priority: 6,
  },
  {
    slug: "face-pull",
    name: "Face pull",
    category: "SHOULDERS",
    equipment: "CABLE",
    compound: false,
    avoidInjuries: [],
    priority: 7,
  },
  {
    slug: "barbell-curl",
    name: "Підйом на біцепс (штанга)",
    category: "ARMS",
    equipment: "BARBELL",
    compound: false,
    avoidInjuries: ["ELBOW", "WRIST"],
    priority: 7,
  },
  {
    slug: "hammer-curl",
    name: "Молоткові згинання",
    category: "ARMS",
    equipment: "DUMBBELL",
    compound: false,
    avoidInjuries: ["ELBOW"],
    priority: 6,
  },
  {
    slug: "tricep-pushdown",
    name: "Трицепс на блоці",
    category: "ARMS",
    equipment: "CABLE",
    compound: false,
    avoidInjuries: ["ELBOW"],
    priority: 7,
  },
  {
    slug: "skull-crusher",
    name: "Французький жим",
    category: "ARMS",
    equipment: "BARBELL",
    compound: false,
    avoidInjuries: ["ELBOW", "WRIST"],
    priority: 5,
  },
  {
    slug: "plank",
    name: "Планка",
    category: "CORE",
    equipment: "BODYWEIGHT",
    compound: false,
    avoidInjuries: ["LOWER_BACK"],
    priority: 6,
  },
  {
    slug: "crunch",
    name: "Скручування",
    category: "CORE",
    equipment: "BODYWEIGHT",
    compound: false,
    avoidInjuries: ["LOWER_BACK"],
    priority: 5,
  },
  {
    slug: "cable-crunch",
    name: "Скручування на блоці",
    category: "CORE",
    equipment: "CABLE",
    compound: false,
    avoidInjuries: ["LOWER_BACK"],
    priority: 5,
  },
];

export function getCatalogBySlug(slug: string): CatalogExercise | undefined {
  return EXERCISE_CATALOG.find((e) => e.slug === slug);
}

export function isExerciseAllowed(
  ex: CatalogExercise,
  injuries: InjuryFlag[]
): boolean {
  return !ex.avoidInjuries.some((i) => injuries.includes(i));
}
